"""empty message

Revision ID: 8ce0c562d264
Revises: 23a4efe4d238
Create Date: 2023-03-14 18:34:23.496971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce0c562d264'
down_revision = '23a4efe4d238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_course_id', ['course_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint('uq_course_id', type_='unique')

    # ### end Alembic commands ###
