"""empty message

Revision ID: 950bb649a4d6
Revises: af4da17c1dd9
Create Date: 2023-03-17 13:49:27.134865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950bb649a4d6'
down_revision = 'af4da17c1dd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=45), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
