"""empty message

Revision ID: a3f4ca11c8ba
Revises: b875237e23aa
Create Date: 2023-03-15 14:48:55.936712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f4ca11c8ba'
down_revision = 'b875237e23aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint('uq_student_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_student_id', ['student_id'])

    # ### end Alembic commands ###
