"""empty message

Revision ID: b875237e23aa
Revises: 8ce0c562d264
Create Date: 2023-03-14 18:38:07.332037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b875237e23aa'
down_revision = '8ce0c562d264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint('uq_course_id', type_='unique')
        batch_op.create_unique_constraint('uq_student_id', ['student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint('uq_student_id', type_='unique')
        batch_op.create_unique_constraint('uq_course_id', ['course_id'])

    # ### end Alembic commands ###
